---
# tasks file for nginx

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: setting nginx
  copy:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-available/default.backup
    remote_src: yes

- name: Replace nginx default
  template:
    src: templates/default
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx