---
- name: Install Application 
  hosts: centos
  connection: ssh
  become: yes
  gather_facts: no

  tasks:
   - name: pip-packages are installed
     pip:
       name: 
         - docker>=1.8.0
         - PyYAML>=3.11
         - docker-compose>=1.7.0
      
   - name: Docker yum utils
     yum:
       name: yum-utils
       state: latest

   - name: Add Docker repo
     get_url: 
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docker-ce.repo

   - name: Install Docker
     yum:
       name:
         - docker-ce
         - docker-ce-cli
         - containerd.io  
       state: present    

   - name: Start the Docker service
     systemd:      
       name: docker
       state: started
       enabled: yes
     
   - name: Add user to docker group
     user:
       name:  artem
       groups: docker
       append: yes
       
   - name: Deploy Docker Image
     docker_container:
       name: application
       image: temkaxd96/application:latest
       pull: yes
       restart_policy: always
       ports: 
         - 8080:8080      
       env:
          - MYSQL_URL=jdbc:mysql://mysql/petclinic
          - MYSQL_USER=petclinic
          - MYSQL_PASS=petclinic
